# Generated by Django 3.1.5 on 2021-07-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='images',
        ),
    ]
